#!/bin/bash
# PHP CodeSniffer pre-commit hook for git
#
# @author Soenke Ruempler <soenke@ruempler.eu>
# @author Sebastian Kaspari <s.kaspari@googlemail.com>
#
# see the README

PHPCS_BIN=./vendor/bin/phpcs
PHPCS_CODING_STANDARD=phpcs.xml
PHPCS_FILE_PATTERN="\.php$"

# simple check if code sniffer is set up correctly
if [ ! -x $PHPCS_BIN ]; then
    echo "PHP CodeSniffer bin not found or executable -> $PHPCS_BIN"
    exit 1
fi

# stolen from template file
if git rev-parse --verify HEAD
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# this is the magic: 
# retrieve all files in staging area that are added, modified or renamed
# but no deletions etc
FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- | egrep $PHPCS_FILE_PATTERN)

if [ "$FILES" == "" ]; then
    exit 0
fi
$PHPCS_BIN --standard=$PHPCS_CODING_STANDARD --encoding=utf-8 -n $FILES
