<?php
/**
 *  Copyright 2015 Ye Wenbin
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
namespace PhalconX\Test\Models;

/**
 * The model Pet.
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 */
class Pet implements \ArrayAccess
{
    /**
     * The id.
     *
     * @Valid(type=integer)
     */
    public $id; /* int */

    /**
     * The category.
     *
     * @IsA(Category)
     */
    public $category; /* Category */

    /**
     * The name.
     *
     * @Valid(required=true)
     */
    public $name; /* string */

    /**
     * The photo_urls.
     *
     * @Valid(required=true, type=array, elementType=string)
     */
    public $photo_urls; /* array[string] */

    /**
     * The tags.
     *
     * @IsA("Tag[]")
     */
    public $tags; /* array[Tag] */

    /**
     * pet status in the store
     */
    public $status; /* string */

    public function __construct(array $data = null)
    {
        if ($data === null) {
            return;
        }
        if (isset($data["id"])) {
            $this->id = $data["id"];
        }
        if (isset($data["category"])) {
            $this->category = $data["category"];
        }
        if (isset($data["name"])) {
            $this->name = $data["name"];
        }
        if (isset($data["photo_urls"])) {
            $this->photo_urls = $data["photo_urls"];
        }
        if (isset($data["tags"])) {
            $this->tags = $data["tags"];
        }
        if (isset($data["status"])) {
            $this->status = $data["status"];
        }
    }
  
    public function offsetExists($offset)
    {
         return isset($this->$offset);
    }
  
    public function offsetGet($offset)
    {
         return $this->$offset;
    }
  
    public function offsetSet($offset, $value)
    {
         $this->$offset = $value;
    }
  
    public function offsetUnset($offset)
    {
         unset($this->$offset);
    }
}
